### ISSUE TITLE
Parsing of address, telephone and individual name ("n") field

### ISSUE THREAD

**Issue by mzpqnxow** [meeb/whoisit#10]
Hey there

First, thank you for this project. I set out to do this about 18 months ago and got sidetracked and settled for partial (and not very elegant) parsing of the vCard data. I'm very appreciative of your work as the data I'm dealing with is both very large (thousands of unique networks) as well as very dispersed- requiring queries to practically every major RIR as well as almost all of the regional RIRs (or at least the ones that have implemented RDAP)

Second, the real reason for entering this, what interest do you have in parsing the following vCard values:

* `adr` (address, 4 element array of strings)
* `tel` (a little more complex but still reasonably simple, a dict with a list, and plain text)
* `n` (4-element array of text, possibly a bit more if done fully)

More direct questions that are more easily answerable if you have the time:

1. Is there a reason you didn't implement the parsing of these fields? I'm speculating you just didn't think the majority of people wanted or needed that level of data, as opposed to them being added complexity you wanted to avoid, but I've considered both as possibilities
2. Are you interested in a PR that adds parsing of these fields? I have this in a fork, it's not terribly invasive, and though it requires more testing before ever going into a stable branch, it's working well for me. I have a need for this data, hence adding it
3. Something I can look into myself, but have you tested this much against APNIC (and the regional RIRs within AsiaPac- China/Japan have a few) or any of the other non-North America RIRs (AFRINIC, LACNIC, RIPE)
4. To what degree are you interested in performing additional normalization or parsing of some of these fields where applicable? For example, passing `tel` or `adr` through a third-party package specializing in those respective types to normalize them? Either as an optional "core" part of the library, or as a Python/setuptools "extra"?

Any answers you can provide are appreciated but if you're too busy to deal with this it's not a problem. I'm happy to work off my own fork for the moment and check in later once it's been more rigorously tested

Thanks again

**Comment by meeb** [comment]
Hi,

Thanks for the issue. Absolutely very happy to accept pull requests that add sensible features. If it keeps within the style I've coded it which is somewhat verbose but easier to come back to after 18 months of not reading it and understand what it's still doing all the better :)

Effectively we had a reasonably narrow use case and built the library to work with that use case. To expand to general use I really just randomly selected a bunch of samples from global RDAP servers of different kinds and tweaked the parser until they seemed to work as expected. So in answer to your specific questions:

1. No specific reason. Likely either didn't encounter them or where I did encounter them they were duplicated.
2. Yep, feel free to submit a PR. Where possible the general aim of the "condensed" or "parsed" results was to return singular checked information, so if you want to try and add an extractor for a single true address string or single true phone number string etc. that would be fine.
3. The library is well tested against network RDAP results, less so against regional ccTLD RDAP servers. Coverage seems reasonably comprehensive, but likely has the odd parsing issue with some of the more esoteric RDAP servers on the internet.
4. Depends on the additional parsing really. If it's relatively basic and pure Python, probably fine. I'd generally like to keep the library simple and not depend on anything too crazy though.

Having taken a look at your sample output probably the only change I'd suggest is making the address a string were possible. The mix of comma-split single lines as a one element list vs. multi-element lists is messy. Also stripping the errant \r and \n etc. would probably be neater.

Generally, if you just add `address` as a clean, parsed string and `phone` and so on, sounds good. These additional parsers would need tests as well.

In your example how does `ind_name` differ from the existing `name` field? What's the raw vcard data there?

**Comment by mzpqnxow** [comment]
Thanks for the quick response

> Absolutely very happy to accept pull requests that add sensible features. If it keeps within the style I've coded it which is somewhat verbose but easier to come back to after 18 months of not reading it and understand what it's still doing all the better :)

Yep, no disagreement there

>     3. The library is well tested against network RDAP results, less so against regional ccTLD RDAP servers. Coverage seems reasonably comprehensive, but likely has the odd parsing issue with some of the more esoteric RDAP servers on the internet.

The good news for you is that it seems to do pretty well against my inputs.I haven't encountered any issues so far, and that includes regional RIRs in Canada, Japan and China

> Having taken a look at your sample output probably the only change I'd suggest is making the address a string were possible. The mix of comma-split single lines as a one element list vs. multi-element lists is messy

Good feedback. I think that may get to be a little tricky because of how unruly and inconsistent the address data can be, but I'll keep it in mind. I'll at least make it easy so it's easy for you to choose which of 2 or 3 styles to keep when I send the PR in (format 1, format2, raw, etc)

> Also stripping the errant \r and \n etc. would probably be neater.

Man, you've got good eyesight! I hadn't even noticed, I'll make sure it strips any other whitsespace as well. As it is now, if an address element ended with a space (or newline, even) it would have ended up in there too- oops!

> In your example how does `ind_name` differ from the existing `name` field? What's the raw vcard data there?

I'll paste that in a separate comment in a moment

**Comment by meeb** [comment]
According to the RFC `fn` and `n` should be equivalent, just `fn` is formatted as a single string and `n` is multi-part, represented as a list in JSON:

https://www.w3.org/2002/12/cal/rfc2426.html#sec3.1.1

https://www.w3.org/2002/12/cal/rfc2426.html#sec3.1.2

I don't *think* there should be a situation where `n` is set but `fn` is not, but I'm fine with the idea of a fallback to `', '.join(n)` if `fn` is not present in the data.

The general aim of the library was to be logical for humans, so, if the data is extracted in a way of "this entity as an abuse contact, and their name is [person/company]" if that makes sense then it's working as intended.

I don't see anything we can really do for organisations or individuals in the wrong fields, they've literally put the individual down as "Rackspace Com" as first and last name in your example. In these sorts of situations the library should probably just return the data verbatim, it will be a bit incorrect, but the source data is incorrect.

**Comment by mzpqnxow** [comment]
> According to the RFC `fn` and `n` should be equivalent, just `fn` is formatted as a single string and `n` is multi-part, represented as a list in JSON:
> 
> https://www.w3.org/2002/12/cal/rfc2426.html#sec3.1.1
> 
> https://www.w3.org/2002/12/cal/rfc2426.html#sec3.1.2
> 
> I don't _think_ there should be a situation where `n` is set but `fn` is not, but I'm fine with the idea of a fallback to `', '.join(n)` if `fn` is not present in the data.
> 

Thank you for those references. For now, I'm going to add an assert on my local copy and see if I encounter a single case where this happens in practice (`n` is set, `fn` is not) - if I don't encounter anything in the next few months then I won't bother to clutter things

> I don't see anything we can really do for organisations or individuals in the wrong fields, they've literally put the individual down as "Rackspace Com" as first and last name in your example. In these sorts of situations the library should probably just return the data verbatim, it will be a bit incorrect, but the source data is incorrect.

Yep, I agree 100% with this, especially now that I've been dealing with the wrangling of bad data almost daily for the past 2 years- you can either drive yourself nuts trying to accomodate bad data (and still end up with bad data) or just "let it be" - it's arguably more correct in the original form anyway

Thanks again, I'll let you know if/when I send something in

**Comment by meeb** [comment]
Sounds good! Thanks for the discussion. As said feel free to submit a PR and I'll be happy to review it. You OK if I close this issue for now?

**Comment by mzpqnxow** [comment]
Closing this out for now. Thanks!
