### ISSUE TITLE
No valid RDAP service URLs could be parsed

### ISSUE THREAD

**Issue by mmlange** [meeb/whoisit#12]
When starting my app, I get this message from whoisit:

Python310\site-packages\whoisit\bootstrap.py", line 206, in validate_rdap_urls
    raise BootstrapError(f'No valid RDAP service URLs could be parsed '
whoisit.errors.BootstrapError: No valid RDAP service URLs could be parsed from: ['http://cctld.uz:9000/']

I'm running this under Python 3.10.5 under Windows, but I also see it in my Docker container.

I suspect it's related to the port in the URL, but I haven't done any testing to confirm this.

**Comment by mmlange** [comment]
I dug into it a bit more and see that the only protocol that is permitted to be used is https.  If I override the PERMITTED_RDAP_PROTOCOLS variable in the Bootstrap class, I can get it to work.  For example:
whoisit._bootstrap.PERMITTED_RDAP_PROTOCOLS = ( 'http', 'https')

Would it be possible to expose this through a method?

**Comment by meeb** [comment]
Thanks for the issue. I didn't really expect the IANA to add RDAP endpoints over HTTP but I guess they have. I've patched this in the above commit so it will silently skip insecure endpoints but emit a debug log. If you need to query objects from insecure RDAP endpoints (for example in this issue, `.uz` / Uzbekistanian domains) you can bootstrap with `whoisit.bootstrap(allow_insecure=True)` to enable them (defaults to `False`). I'll roll this patch up into a new 2.6.0 release shortly.
