### ISSUE TITLE
Mutable defaults parameters en request wrapper

### ISSUE THREAD

**Issue by Laikos38** [meeb/whoisit#14]
Hi! Just a recommendation, in `utils.py` this method is using mutable defaults parameters, which are not a good practice.

```python
def http_request(session, url, method='GET', allow_insecure_ssl=False,
                 headers={}, data={}, *args, **kwargs):
```

[Source/explanation](https://stackoverflow.com/questions/26320899/why-is-the-empty-dictionary-a-dangerous-default-value-in-python)

A simple fix should be 
```python
def http_request(session, url, method='GET', allow_insecure_ssl=False,
                 headers=None, data=None, *args, **kwargs):
    headers = headers or {}
    data = data or {}
```

**Comment by meeb** [comment]
A reasonable point. In the context that `http_request` is used it's not an issue, but I'll fix it for the next release anyway.
