### ISSUE TITLE
Failure when sld require different url than tld

### ISSUE THREAD

**Issue by tmuncks** [meeb/whoisit#16]
In a number of countries, GL for one, in addition to the TLD 'gl', an SLD is used for domains. The effective 'tld' to be handled by whoisit then becomes something like 'co.gl' or 'net.gl' which it does not currently support.

I have set this up with custom overrides like this:

```
whoisit.overrides.iana_overrides['domain'] = {
    'gl': ['https://rdap.centralnic.com/gl/'],
    'co.gl': ['https://rdap.centralnic.com/co.gl/'],
    'net.gl': ['https://rdap.centralnic.com/net.gl/']
}
```

I need something like this, because CentralNIC requires different base urls for these slds. Due to how the lookup is handled in `get_domain_endpoint` however, it does not currently work.

**Comment by meeb** [comment]
`whoisit` by default directly refers queries to RDAP endpoints as listed in the IANA bootstrap data. If these ccTLDs aren't resolving properly than that's the exact use case the overrides facility exists. Feel free to submit a PR with these overrides added and I'll give it a test. The only issue here is if a ccTLD has an RDAP endpoint that's not referred to by the IANA initial hint data the response format may be non-standard so some of the parsed data might be missing some values (so you may need to use `raw=True` for example).

Happy to add any relatively sensible overrides into the next release though if you want to suggest some.

**Comment by tmuncks** [comment]
The problem is more that the code does not support looking up the RDAP endpoint for an sld, only for an tld.

So `whoisit.domain('example.net.gl')` will always only look for `gl` in the bootstrap data, not `net.gl` which is what is required for centralnic.

It's described at https://centralnicregistry.com/support/information/rdap:

_Unfortunately, since the IANA can only accept registrations for top-level domains, CentralNic's SLD portfolio cannot be added to the registry. However, the RDAP service is available for these domains, at https://rdap.centralnic.com/{sld}._

I will happily submit a PR to support this type of overrides, if it seems acceptable to you.

**Comment by meeb** [comment]
Ah right sorry I didn't follow that was the issue originally. It should be relatively easy to add SLD support for TLDs that don't explicitly list the SLDs. I'll pop it into the next release. Thanks for the detailed issue.

**Comment by tmuncks** [comment]
Sounds good. Thank you.

FWIW, I did raise the issue with centralnic as there are many other advantages to using the same RDAP endpoint for all domains under a tld (including the slds). I do feel that adding support here will be both easier and certainly add some flexibility to things at the same time.

**Comment by meeb** [comment]
`v2.6.4` which is just released now should support second level domain overrides. I've added your `gl` overrides to `overrides.py` as well.

**Comment by tmuncks** [comment]
Works absolutely perfectly! Thank you.

For the sake of completeness, this is the full list of GL SLDs. The change to the actual lookup code was all I was hoping for, so I'm more than happy to simply provide my own overrides, but I want you to at least be aware of these.

Thanks again.

```
'gl': ['https://rdap.centralnic.com/gl/'],
'co.gl': ['https://rdap.centralnic.com/co.gl/'],
'com.gl': ['https://rdap.centralnic.com/com.gl/'],
'edu.gl': ['https://rdap.centralnic.com/edu.gl/'],
'gov.gl': ['https://rdap.centralnic.com/gov.gl/'],
'net.gl': ['https://rdap.centralnic.com/net.gl/'],
'org.gl': ['https://rdap.centralnic.com/org.gl/']
```

**Comment by meeb** [comment]
Sure, updated the `gl` override list but I won't do a full release now just for those so they'll be in the next release whenever that is.
