### ISSUE TITLE
Can the route information be returned when using whois + IP?

### ISSUE THREAD

**Issue by jackfish0405** [meeb/whoisit#24]
hi
When using the whois command under Linux, there will be route-related information. This part is not included in the information returned by whoisit. Is it possible to obtain this information? Thanks

For example
 
whois  14.204.0.0/15

At the end there is the following information:

**% Information related to '14.204.0.0/15AS4837'

route:          14.204.0.0/15
descr:          China Unicom Yunnan Province Network
country:        CN
origin:         AS4837
mnt-by:         MAINT-CNCGROUP-RR
last-modified:  2010-09-26T02:26:02Z
source:         APNIC**

% This query was served by the APNIC Whois Service version 1.88.25 (WHOIS-AU3)

**Comment by jackfish0405** [comment]
Thank you very much, this is exactly what I was looking for. Testing IPNet DB data is more accurate than ipwhois query in querying routing information.

**Comment by meeb** [comment]
Indeed, it is going to be a lot more accurate. IPNetDB is generated from hundreds of full routing tables overlapped on each other and should be very accurate. The only downside is you need to update the database weekly, however it is much faster to query.

Feel free to contact us at licence@ipnetdb.com if you need a commercial or closed source licence for your project.

Are you happy to close this issue?

**Comment by jackfish0405** [comment]
OK, thanks
