### ISSUE TITLE
Follow related links

### ISSUE THREAD

**Issue by dumkydewilde** [meeb/whoisit#26]
Many RDAP requests are returned with a related link containing more information about the domain. For example, the `.com` domain is handled by Verisign, but Verisign might return a related link to the registrar for more information. For example, looking up [amazon.com](https://client.rdap.org/?type=domain&object=amazon.com) will yield [a link to the registrar](https://client.rdap.org/?type=url&object=https%3A//rdap.markmonitor.com/rdap/domain/AMAZON.COM) (MarkMonitor) with more information.

I feel like this might be a nice addition for convenience, maybe by adding an optional parameter for following relations. I currently have a super simple implementation as follows, which definitely has room for improvement. If you are interested or have additional thoughts, I am happy to create a PR.

```
tld_domain = "amazon.com"
result = whoisit.domain(tld_domain, raw=True)

for link in result.get("links", []):
    if link["rel"] in ["related", "registration"]:
        res = requests.get(link.get("href", ""))
        result = res.json() # overwrite result if a related link was followed

parsed_result = whoisit.parse(whoisit._bootstrap, "domain", tld_domain, result)
```

**Comment by meeb** [comment]
That sounds a sensible suggestion. Thanks for the example!

**Comment by meeb** [comment]
This is bundled into the latest release and is enabled by default, you won't need your hack any longer. Thanks again for the suggestion.

**Comment by dumkydewilde** [comment]
This is amazing! Thanks for fixing 👌
