### ISSUE TITLE
Exception 'AttributeError' raise for some domains

### ISSUE THREAD

**Issue by yaksnip425** [meeb/whoisit#28]
The exception "AttributeError: 'list' object has no attribute 'get'"  for [parser.py at line 192](https://github.com/meeb/whoisit/blob/ad69a22c063345187a6c9fb0247002eeb57f7e45/whoisit/parser.py#L192) is raise for some domains like jeldwen.com when call with `whoisit.domain(domain_name=domain, allow_insecure_ssl=True)` since release 2.7.4.

**Comment by meeb** [comment]
Ah, this is because the RDAP data returned by the subrequest as of 2.7.4 is returning data in a slightly invalid structure. I'll ignore it.

**Comment by meeb** [comment]
Also just added a `follow_related` arg for `whoisit.domain(...)` where you can set `follow_related=False` and `whoisit` won't make subrequests. You can use this as a fallback if the initial query fails. Usage:

`whoisit.domain('example.com', follow_related=False)`

Both the above will be bundled into a 2.7.6 release shortly.

**Comment by meeb** [comment]
2.7.6 is available now.
