### ISSUE TITLE
Feature request: Releases

### ISSUE THREAD

**Issue by case** [meeb/whoisit#4]
Hi @meeb,

I was wondering if you'd consider adding git tags for new releases here? Then GitHub can auto-generate changelogs from the all the commits that go into a new release.

https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

> Releases are based on Git tags, which mark a specific point in your repository's history.

Thanks for considering!

**Comment by meeb** [comment]
Sure, could do. Most people just use PyPI and don't look at the releases on here so I'd not bothered so far.

**Comment by meeb** [comment]
There you go: https://github.com/meeb/whoisit/releases

The changelog is just a list to the commits though so not entirely sure how useful the automated docs are...

**Comment by case** [comment]
Thanks!
