### ISSUE TITLE
error_content not defined when HTTP 200

### ISSUE THREAD

**Issue by askkemp** [meeb/whoisit#42]
When HTTP 200 is returned, but the response content is not JSON, then the below error occurs. The issue is that the variable `error_content` is only defined when the response code is `!=200` or when the response code is in `status_code_map` ([see here](https://github.com/meeb/whoisit/blob/main/whoisit/query.py#L250)). When the response code is 200, but the content is HTML, then the exception occurs but `error_content` is not populated thus a UnboundLocalError is caused.

```
  File "/whoisit-3.0.0/whoisit/query.py", line 268, in _process_response
    raise QueryError(f'Failed to parse RDAP Query response as JSON: {e}', response=error_content) from e
                                                                                   ^^^^^^^^^^^^^
  UnboundLocalError: cannot access local variable 'error_content' where it is not associated with a value
```

I only see this condition occur when the RDAP provider performs a 302 redirect to another URL which then returns HTML.

**Comment by meeb** [comment]
Thanks for the issue. I've fixed the missing `error_content` variable in the above commit. Can you give me an example where this was triggered? Obviously an RDAP endpoint redirecting to a URL that returns HTML is pretty broken and might be worth reporting.
